plugins:
  - import

parser: '@typescript-eslint/parser'

# parserOptions:
#   sourceType: module
#   ecmaVersion: 2020

rules:
  no-undef: error
  import/named: error
  import/namespace: error

settings:
  import/resolver:
    typescript: {}
  react:
    version: detect